[package]
name = "libp2p_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
libp2p = { version = "0.54.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
